<?php
namespace tests\web;

use liw\Controller;
use liw\Faker;
use liw\web\Application;
use PHPUnit\Framework\TestCase;

/**
 * Class ApplicationTest
 *
 * @package tests\web
 */
class ControllerTest extends TestCase
{
    /** @var  Application */
    protected $app;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->app = new Application();
    }


    public function testCreateController()
    {
        $this->assertInstanceOf(Controller::class, $this->app->Controller);
    }
}
